import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const { records = [], dataset_name = "Active Dataset", title } = await req.json();

    if (!records || records.length === 0) {
      return NextResponse.json({ detail: "No records provided" }, { status: 400 });
    }

    const nRows = records.length;
    const cols = Object.keys(records[0]);
    const nCols = cols.length;

    let totalNulls = 0;
    const numericCols: string[] = [];
    const catCols: string[] = [];

    cols.forEach((col) => {
      let isNum = true;
      records.forEach((row: any) => {
        const val = row[col];
        if (val === null || val === undefined || val === "") totalNulls++;
        else if (typeof val !== "number") isNum = false;
      });
      if (isNum) numericCols.push(col);
      else catCols.push(col);
    });

    const completeness = Math.max(0, 100 - (totalNulls / (nRows * nCols)) * 100).toFixed(1);
    const reportTitle = title || `Executive Intelligence Analysis — ${dataset_name}`;
    const now = new Date().toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });

    const lines = [
      `# ${reportTitle}`,
      `> **Generated by DataMind AI** · Groq LPU Analytical Engine · ${now}\n`,
      `## 1. Dataset Architecture & Health Scorecard`,
      `- **Volume:** ${nRows.toLocaleString()} observations across **${nCols}** feature dimensions`,
      `- **Data Completeness:** **${completeness}%** (${totalNulls} missing cells detected)`,
      `- **Dimensionality:** ${numericCols.length} quantitative features, ${catCols.length} categorical features\n`,
      `## 2. Key Quantitative Indicators`,
    ];

    numericCols.slice(0, 5).forEach((col) => {
      const vals = records
        .map((r: any) => Number(r[col]))
        .filter((v: number) => !isNaN(v));
      if (vals.length > 0) {
        const avg = (vals.reduce((a: number, b: number) => a + b, 0) / vals.length).toFixed(2);
        const min = Math.min(...vals).toFixed(2);
        const max = Math.max(...vals).toFixed(2);
        lines.push(`- **\`${col}\`**: Mean = **${avg}** | Range = [${min}, ${max}]`);
      }
    });

    if (catCols.length > 0) {
      lines.push(`\n## 3. Dominant Categorical Segments`);
      catCols.slice(0, 3).forEach((col) => {
        const counts: Record<string, number> = {};
        records.forEach((r: any) => {
          const val = String(r[col] ?? "");
          if (val) counts[val] = (counts[val] || 0) + 1;
        });
        const top = Object.entries(counts).sort((a, b) => b[1] - a[1])[0];
        if (top) {
          lines.push(`- **\`${col}\`**: Leading segment is **${top[0]}** (${top[1]} records)`);
        }
      });
    }

    lines.push(
      `\n## 4. Strategic Recommendations`,
      `1. **Automated Validation**: Establish automated schema validation to protect the **${completeness}%** completeness rate.`,
      `2. **Anomaly Alerting**: Set dynamic thresholds on primary quantitative features to catch statistical outliers.`,
      `3. **Continuous Ingestion**: Stream incoming records directly into the Groq LPU pipeline for real-time reporting.`
    );

    return NextResponse.json({
      status: "success",
      report_markdown: lines.join("\n"),
    });
  } catch (error: any) {
    return NextResponse.json({ detail: error?.message || "Error generating report" }, { status: 500 });
  }
}
